# ==================== 站点配置 ====================
site_name: CS/AI 技术博客
site_url: https://wiki.dwj601.cn/
repo_url: https://github.com/Explorer-Dong/wiki
repo_name: Explorer-Dong/wiki
edit_uri: edit/main/docs/
copyright: '&copy; 2026 Explorer Dong'


# ==================== 预览配置 ====================
watch:
  - overrides/


# ==================== 主题配置 ====================
theme:
  # variant: classic
  name: material
  language: zh
  custom_dir: overrides
  # 图标
  logo: assets/logo.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  # 颜色
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换到亮色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到自动模式
  features:
    # - header.autohide              # 自动隐藏页面头部
    - navigation.tabs                # 顶部一级分类导航栏
    # - navigation.tabs.sticky         # 固定顶部一级分类导航栏
    - navigation.sections          # 分类页小标题
    # - navigation.expand            # 分类页默认展开
    - navigation.indexes           # 不显示分类索引首页
    - navigation.top               # 顶部导航栏
    - navigation.path              # 路径导航
    - navigation.instant.preview   # 预加载内链
    - navigation.footer            # 页脚
    - content.code.copy            # 代码块复制按钮
    - content.code.select          # 代码块选中行
    - content.tooltips             # 内容悬浮提示
    - content.action.edit          # 编辑源文件按钮
    - content.action.view          # 查看源文件按钮
    - content.tabs.link            # 同名标签一起切换
    - search.highlight             # 搜索结果高亮
    - search.share                 # 社交分享按钮
    - search.suggest               # 搜索建议
    - toc.follow                   # 目录跟随滚动（需要 markdown_extensions.toc.permalink 开启）
    # - announce.dismiss             # 支持手动关闭公告


# ==================== 语法扩展 ====================
markdown_extensions:
  - abbr               # 悬浮缩写
  - attr_list          # 给 md 添加 HTML 属性和 CSS 类
  - md_in_html         # 允许在 HTML 中写 md
  - admonition         # 内容框（例如 tip、note、warning 等）
  - footnotes          # 脚注
  - toc:               # 目录
      permalink: true             # 显示标题链接
      toc_depth: 3                # 显示目录深度
      title: 本页目录             # 目录标题
      permalink_title: 页面定位   # 链接标题
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}

  - pymdownx.snippets      # 嵌入外部文件（例如代码）
  - pymdownx.details       # 允许内容框折叠
  - pymdownx.tabbed:       # 并列展示内容（需要和 superfences 一起使用）
      alternate_style: true
  - pymdownx.superfences:  # 允许嵌套
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:   # 优化数学公式
      generic: true
  - pymdownx.emoji:        # 支持表情符号
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:    # 高亮行间代码
      auto_title: true           # 自动标题
      use_pygments: true         # 第三方库增强
      pygments_lang_class: true  # 语言定制化高亮
      linenums: true             # 显示行号
      anchor_linenums: true      # 行号锚点
      line_spans: __span         # 行号容器（移动端适配）
  - pymdownx.inlinehilite  # 高亮行内代码
  - pymdownx.tasklist:     # 支持任务列表
      custom_checkbox: true


# ==================== 样式注入 ====================
extra_javascript:
  # KaTeX
  - https://registry.npmmirror.com/katex/0.16.21/files/dist/katex.min.js
  - https://registry.npmmirror.com/katex/0.16.21/files/dist/contrib/auto-render.min.js
  # mermaid
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/11.12.0/mermaid.min.js
  # 自定义 JS 脚本
  - assets/extra.js
extra_css:
  # KaTeX
  - https://registry.npmmirror.com/katex/0.16.21/files/dist/katex.min.css
  # 自定义 CSS 样式
  - assets/extra.css


# ==================== 插件配置 ====================
plugins:
  # 搜索功能
  - search:
      lang: zh
  # 显示文章创建和修改时间
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
      type: date
      timezone: Asia/Shanghai
  # 显示文章作者（头像与 GitHub Profile 链接）
  - git-committers:
      enabled: !ENV [CI, false]
      repository: Explorer-Dong/wiki
      branch: main
  # 图片可点击放大
  - glightbox:
      auto_caption: false
  # meta 配置
  - meta:
      enabled: !ENV [CI, false]
  # 隐藏侧边栏行为
  - toggle-sidebar:
      theme: material
      toggle_button: all
      button_toggle_both_tooltip: 折叠或展开文件列表和页面目录


# ==================== 额外配置 ====================
extra:
  # 谷歌分析
  analytics:
    provider: google
    property: G-56NDVC0D5B
  # 文章状态定义
  status:
    new: 待更新
    deprecated: 即将废弃
  # 页面底部社交链接
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Explorer-Dong
      name: GitHub
    - icon: fontawesome/solid/c
      link: https://blog.csdn.net/qq_73408594
      name: CSDN
    - icon: simple/zhihu
      link: https://www.zhihu.com/people/dwj601
      name: 知乎
    - icon: clover-solid
      link: https://blog.dwj601.cn/
      name: 生活博客


# ==================== 页面导航 ====================
nav:
  - index.md
  - 基础知识:
    - base/index.md
    - 人工智能基础:
      - 数字图像处理:
        - base/ai/digital-image-processing/index.md
      - 机器学习:
        - base/ai/machine-learning/index.md
        - base/ai/machine-learning/data-process.md
        - base/ai/machine-learning/model-select.md
        - base/ai/machine-learning/linear-model.md
        - base/ai/machine-learning/decision-tree-model.md
        - base/ai/machine-learning/bayes-model.md
        - base/ai/machine-learning/probability-graph-model.md
        - base/ai/machine-learning/ensemble-learning.md
        - base/ai/machine-learning/lazy-learning.md
        - base/ai/machine-learning/cluster-learning.md
        - base/ai/machine-learning/semi-supervised-learning.md
      - 数据挖掘:
        - base/ai/data-mining/index.md
        - base/ai/data-mining/association-analysis.md
        - base/ai/data-mining/anomaly-detection.md
      - 深度学习:
        - base/ai/deep-learning/index.md
        - base/ai/deep-learning/full-connect-neural-network.md
        - base/ai/deep-learning/convolutional-neural-network.md
        - base/ai/deep-learning/recurrent-neural-network.md
        - base/ai/deep-learning/network-enhancement.md
      - 强化学习:
        - base/ai/reinforcement-learning/index.md
      - 语音信号处理:
        - base/ai/speech-signal-processing/index.md
      - 自然语言处理:
        - base/ai/natural-language-processing/index.md
        - base/ai/natural-language-processing/word-embedding.md
        - base/ai/natural-language-processing/text-classification.md
        - base/ai/natural-language-processing/text-generation.md
      - 计算机视觉:
        - base/ai/computer-vision/index.md
        - base/ai/computer-vision/image-classification.md
        - base/ai/computer-vision/object-detection.md
        - base/ai/computer-vision/image-super-resolution.md
        - base/ai/computer-vision/video-understanding.md
    - 计算机基础:
      - 面向对象程序设计:
        - base/cs/object-oriented-programming/index.md
      - 数字逻辑电路:
        - base/cs/digital-logic-circuit/index.md
      - 计算机系统基础:
        - base/cs/computer-system-base/index.md
        - base/cs/computer-system-base/data-represent-and-process.md
        - base/cs/computer-system-base/program-transform-and-represent.md
        - base/cs/computer-system-base/program-link.md
      - 数据库:
        - base/cs/database/index.md
      - 操作系统:
        - base/cs/operating-system/index.md
        - base/cs/operating-system/concurrent.md
        - base/cs/operating-system/virtualization.md
        - base/cs/operating-system/persistence.md
      - 计算机组成:
        - base/cs/computer-organization/index.md
        - base/cs/computer-organization/cpu.md
        - base/cs/computer-organization/memory.md
        - base/cs/computer-organization/device.md
      - 计算机网络:
        - base/cs/computer-network/index.md
        - base/cs/computer-network/application-layer.md
        - base/cs/computer-network/transport-layer.md
        - base/cs/computer-network/network-layer.md
        - base/cs/computer-network/data-link-layer.md
        - base/cs/computer-network/physical-layer.md
    - 数学基础:
      - 高等数学:
        - base/math/advanced-math/index.md
        - base/math/advanced-math/differentiation.md
        - base/math/advanced-math/integration.md
      - 线性代数:
        - base/math/linear-algebra/index.md
        - base/math/linear-algebra/determinant.md
        - base/math/linear-algebra/matrix.md
        - base/math/linear-algebra/elementary-transformation.md
        - base/math/linear-algebra/vector-group.md
        - base/math/linear-algebra/similarity-matrix.md
      - 概率统计:
        - base/math/probability-and-statistics/index.md
        - base/math/probability-and-statistics/prob.md
        - base/math/probability-and-statistics/stat.md
      - 优化方法:
        - base/math/optimization-method/index.md
        - base/math/optimization-method/linear-search.md
        - base/math/optimization-method/unconstraint-optimization.md
        - base/math/optimization-method/constraint-optimization.md
    - 其他:
      - 大学物理:
        - base/others/college-physics/index.md
      - 英语语法:
        - base/others/english-grammar/index.md
        - base/others/english-grammar/word-property.md
        - base/others/english-grammar/sentence-ingredient.md
        - base/others/english-grammar/sentence-type.md
  - 数据结构与算法:
    - ds-and-algo/index.md
    - ds-and-algo/templates.md
    - ds-and-algo/templates-py.md
    - 专题解析:
      - ds-and-algo/topic/index.md
      - ds-and-algo/topic/base.md
      - ds-and-algo/topic/ds.md
      - ds-and-algo/topic/dp.md
      - ds-and-algo/topic/geometry.md
      - ds-and-algo/topic/string.md
      - ds-and-algo/topic/graph.md
      - ds-and-algo/topic/math.md
      - ds-and-algo/topic/others.md
    - 蓝桥杯备赛指南:
      - ds-and-algo/lan-qiao-cup/index.md
      - ds-and-algo/lan-qiao-cup/16th-python-a-nation.md
      - ds-and-algo/lan-qiao-cup/16th-python-a.md
      - ds-and-algo/lan-qiao-cup/15th-python-a.md
      - ds-and-algo/lan-qiao-cup/14th-python-a.md
  - 软件开发:
    - develop/index.md
    - 前端:
      - develop/front-end/index.md
      - develop/front-end/html.md
      - develop/front-end/css.md
      - JavaScript:
        - develop/front-end/javascript/index.md
        - develop/front-end/javascript/grammar.md
    - 后端:
      - develop/back-end/index.md
      - C++:
        - develop/back-end/cpp/index.md
        - develop/back-end/cpp/grammar.md
        - develop/back-end/cpp/std-lib.md
      - Python:
        - develop/back-end/python/index.md
        - develop/back-end/python/grammar.md
        - develop/back-end/python/std-lib.md
        - develop/back-end/python/async-lib.md
        - develop/back-end/python/network-lib.md
        - develop/back-end/python/compute-lib.md
        - develop/back-end/python/data-analyze-lib.md
        - develop/back-end/python/visual-lib.md
    - 数据库:
      - develop/database/index.md
      - develop/database/mysql.md
      - develop/database/redis.md
    - 运维:
      - develop/operation/index.md
      - develop/operation/linux.md
      - develop/operation/windows.md
      - develop/operation/wsl2.md
      - develop/operation/shell.md
      - develop/operation/nginx.md
      - develop/operation/docker.md
    - 工具:
      - develop/tools/index.md
      - develop/tools/hexo.md
      - develop/tools/ssh.md
      - 编辑器:
        - develop/tools/editor/index.md
        - develop/tools/editor/devcpp.md
        - develop/tools/editor/idle.md
        - develop/tools/editor/vim.md
        - develop/tools/editor/vscode.md
        - develop/tools/editor/jetbrains.md
      - Git:
        - develop/tools/git/index.md
        - develop/tools/git/commands.md
        - develop/tools/git/lfs.md
        - develop/tools/git/submodule.md
        - develop/tools/git/github.md
        - develop/tools/git/branch-conflict.md
    - 其他:
      - develop/others/data-serialization-format.md
      - develop/others/cli-argument-format.md
  - 大模型:
    - llm/index.md
    - 基础设施:
      - llm/infra/index.md
      - llm/infra/accelerator.md
      - llm/infra/huggingface.md
      - llm/infra/pytorch.md
      - llm/infra/serving-framework.md
    - 模型原理:
      - llm/model/index.md
      - Transformer Model:
        - llm/model/transformer/index.md
      - Diffusion Model:
        - llm/model/diffusion/index.md
    - 下游应用:
      - llm/downstream/index.md
      - llm/downstream/prompt-engineering.md
    - 科研范式:
      - llm/research/index.md
      - llm/research/paper-writing.md
  - contributing.md
